<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Superpayments\SuperPayment\ViewModel\MarketingBanner $viewModel */
/** @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var \Magento\Framework\Escaper $escaper */

$viewModel = $block->getData('view_model');

$config = [
    'integrationId'       => (string) $viewModel->getIntegrationId(),
    'platform'            => 'magento',
    'platformVersion'     => (string) ($viewModel->getConfig()->getMagentoVersion() . '-' . $viewModel->getConfig()->getMagentoEdition()),
    'superPluginVersion'  => (string) $viewModel->getConfig()->getModuleVersion(),
    'sdkVersion'          => (string) $viewModel->getConfig()->getModuleVersion(),
    'page'                => (string) $viewModel->getPage(),
    'isDebugEnabled'      => (bool) $viewModel->getConfig()->isDebugEnabled(),
    'currency'            => (string) $viewModel->getStoreCurrencyCode(),
    'enableForCurrencies' => ['GBP'],
];

$configJson = json_encode(
    $config,
    JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT
);

$publishableKey = (string) $viewModel->getPublishableKey();
$cdnUrl        = (string) $viewModel->getCdnUrl();

if (!$viewModel->shouldUseSecureRenderer()):
    ?>
    <script src="<?= $escaper->escapeUrl($cdnUrl); ?>"></script>
    <script>
        superjs.init(
            "<?= $escaper->escapeJs($publishableKey); ?>",
            <?= /* @noEscape */ $configJson ?>
        );
    </script>
<?php else:
    $scriptBody = 'superjs.init("' . $escaper->escapeJs($publishableKey) . '", ' . $configJson . ');';
    ?>

    <?= /* @noEscape */ $secureRenderer->renderTag(
        'script',
        ['type' => 'text/javascript', 'src' => $cdnUrl],
        '',
        false
    ) ?>

    <?= /* @noEscape */ $secureRenderer->renderTag(
        'script',
        ['type' => 'text/javascript'],
        $scriptBody,
        false
    ) ?>

<?php endif; ?>
