<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Superpayments\SuperPayment\ViewModel\MarketingBanner $viewModel */
/** @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var \Magento\Framework\Escaper $escaper */

$viewModel  = $block->getData('view_model');
$bannerMode = $viewModel->getBannerMode();
$isHomePage = $viewModel->getIsHomePage();
$isCheckout = $viewModel->getIsCheckout();
$bannerData = [];

if ($bannerMode === 'allpages' && $isCheckout) {
    $bannerData = $viewModel->getWebComponentData('checkout', true);
} elseif (($bannerMode === 'allpages' && !$isCheckout) || ($bannerMode === 'homepage' && $isHomePage)) {
    $bannerData = $viewModel->getWebComponentData();
}

if (!empty($bannerData)):
    if (!$viewModel->shouldUseSecureRenderer()): ?>
        <script>
            try {
                require(['jquery', 'jquery/ui'], function ($) {
                    $(document).ready(function () {
                        $("#top-super-banner").slideDown('slow');
                    });
                });
            } catch (error) {
                window.addEventListener('load', function () {
                    document.getElementById("top-super-banner").style.display = "block";
                });
            }
        </script>
    <?php else:
        $script = <<<SCRIPT
try {
    require(['jquery', 'jquery/ui'], function($){
        $(document).ready(function() {
            $("#top-super-banner").slideDown('slow');
        });
    });
} catch (error) {
    window.addEventListener('load', function () {
        document.getElementById("top-super-banner").style.display = "block";
    });
}
SCRIPT;
        ?>
        <?= /* @noEscape */ $secureRenderer->renderTag('script', ['type' => 'text/javascript'], $script, false) ?>
    <?php endif;

    $cartAmount = (string)(int)($bannerData['minorUnitAmount'] ?? 0);
    $page       = (string)($bannerData['page'] ?? '');
    $cartId     = (string)($bannerData['cart']['id'] ?? '');
    $cartItems  = (string)$viewModel->cartItemsEncode($bannerData['cart']['items'] ?? []);
    ?>
    <div id="top-super-banner" style="display: none">
        <super-banner
            cartAmount="<?= $escaper->escapeHtmlAttr($cartAmount); ?>"
            page="<?= $escaper->escapeHtmlAttr($page); ?>"
            cartId="<?= $escaper->escapeHtmlAttr($cartId); ?>"
            cartItems="<?= $escaper->escapeHtmlAttr($cartItems); ?>"
        ></super-banner>
    </div>
<?php endif; ?>
