<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Superpayments\SuperPayment\ViewModel\MarketingBanner $viewModel */
/** @var \Magento\Framework\Escaper $escaper */

$viewModel = $block->getData('view_model');

if (!$viewModel->isSuperPaymentOrder() && $viewModel->getPublishersPostCheckoutBanner()):
    $brandId        = (string)($viewModel->getBrandId() ?? '');
    $publishableKey = (string)($viewModel->getPublishableKey() ?? '');
    ?>
    <div class="super-container">
        <style>
            .super-container div[style] {
                font-size: 12px;
            }
        </style>
        <super-publishers-post-checkout
            offer-type="super-brands"
            brand-id="<?= $escaper->escapeHtmlAttr($brandId); ?>"
            publishable-api-key="<?= $escaper->escapeHtmlAttr($publishableKey); ?>"
        ></super-publishers-post-checkout>
    </div>
<?php endif; ?>
