<?php
/**@var Magento\Framework\View\Element\Template $block */
/**@var Superpayments\SuperPayment\ViewModel\MarketingBanner $viewModel */
$viewModel = $block->getData('view_model');
if ($viewModel->isSuperPaymentOrder() && $viewModel->getOrderConfirmationBanner()) {
    $bannerData = $viewModel->getWebComponentData('order-confirmation', false, true);
?>
    <div class="super-container">
        <style>
            .super-container div[style] {
                font-size: 12px;
            }
        </style>
        <?php echo '<super-transaction-reward page="' .  $bannerData['page'] . '" transactionReference="' . $bannerData['transactionReference'] . '" email="' . $bannerData['email'] . '"></super-transaction-rewards>'; ?>
    </div>
<?php } ?>
