<?php
/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 * @var \Magento\Framework\Escaper $escaper
 */

$specificInfo          = $block->getSpecificInformation();
$additionalInformation = (array) $block->getInfo()->getAdditionalInformation();

$storeId       = $block->getInfo()->getOrder()->getStoreId();
$paymentTitle  = (string) $block->getMethod()->getConfigData('title', $storeId);

$paymentMethod = isset($additionalInformation['payment_method'])
    ? (string) $additionalInformation['payment_method']
    : $paymentTitle;
?>

<?= $escaper->escapeHtml($paymentMethod) ?>

<?= /* @noEscape */ $block->getChildHtml() ?>
