<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Superpayments\SuperPayment\ViewModel\PaymentConfirmation $viewModel */
/** @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var \Magento\Framework\Escaper $escaper */

$viewModel     = $block->getData('view_model');
$paymentJsUrl  = (string) $viewModel->getPaymentJsUrl();

if (!$viewModel->shouldUseSecureRenderer()):
    ?>
    <script src="<?= $escaper->escapeUrl($paymentJsUrl); ?>"></script>
<?php else: ?>
    <?= /* @noEscape */ $secureRenderer->renderTag(
        'script',
        ['type' => 'text/javascript', 'src' => $paymentJsUrl],
        '',
        false
    ) ?>
<?php endif; ?>
