<?php
/**@var Magento\Framework\View\Element\Template $block */
/**@var Superpayments\SuperPayment\ViewModel\MarketingBanner $viewModel */
/**@var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
$viewModel = $block->getData('view_model');
if (!$viewModel->isSuperPaymentOrder() && $viewModel->getPublishersPostCheckoutBanner()) {
if (!$viewModel->shouldUseSecureRenderer()) {
?>
    <script src="<?php echo $viewModel->getPublisherJsUrl(); ?>"></script>
<?php
} else {
    echo $secureRenderer->renderTag(
        'script',
        ['type' => 'text/javascript', 'src' => $viewModel->getPublisherJsUrl()],
        "",
        false
    );
}
}
?>
