<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Superpayments\SuperPayment\ViewModel\MarketingBanner $viewModel */
/** @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var \Magento\Framework\Escaper $escaper */

$viewModel = $block->getData('view_model');

if (!$viewModel->isSuperPaymentOrder() && $viewModel->getPublishersPostCheckoutBanner()):
    $publisherJsUrl = (string) $viewModel->getPublisherJsUrl();

    if (!$viewModel->shouldUseSecureRenderer()): ?>
        <script src="<?= $escaper->escapeUrl($publisherJsUrl); ?>"></script>
    <?php else: ?>
        <?= /* @noEscape */ $secureRenderer->renderTag(
            'script',
            ['type' => 'text/javascript', 'src' => $publisherJsUrl],
            '',
            false
        ) ?>
    <?php endif; ?>
<?php endif; ?>
